version: '3.7'

services:
  app:
    container_name: mergeforces_service
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    env_file:
       - ./docker/app/.env
    ports:
      - 8080:8080
    restart: on-failure
    command: ["/usr/local/bin/app/wait-for-db.sh", "db", "/usr/local/bin/app/init.sh"]

  db:
    image: postgres:latest
    container_name: mergeforces_db
    env_file:
      - ./docker/postgres/.env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '5432:5432'

