version: '3.7'

services:
  app:
    container_name: mergeforces_service
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    env_file:
       - ./docker/app/.env
    ports:
      - 8080:8080
    restart: on-failure
